server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5432/token_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.application.name=token-service
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
